all:
  hosts:
    rinoa:
      ansible_host: 192.168.1.254
      ansible_user: charish
    rikku:
      ansible_host: 192.168.1.252
      ansible_user: pi
    benedikta:
      ansible_host: 192.168.1.250
      ansible_user: ovos
