name: Home Assistant Config Check

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'app-configs/rikku/homeassistant/**'
      - '**/homeassistant-config-check.yml'

jobs:
  home-assistant-config-check:
    name: Home Assistant Configuration Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Gotify Notification (start check)
        uses: eikendev/gotify-action@master
        with:
          gotify_api_base: ${{ secrets.GOTIFY_URL }}
          gotify_app_token: ${{ secrets.RUNNER_GOTIFY_TOKEN }}
          notification_title: 'GITEA: Home Assistant Config Check'
          notification_message: 'Starting config check...'

      - name: 🚀 Run Home Assistant Configuration Check
        uses: https://git.trez.wtf/Trez.One/action-home-assistant@main
        with:
          path: "app-configs/rikku/homeassistant"
          version: "stable"

      - name: Gotify Notification (done)
        uses: eikendev/gotify-action@master
        with:
          gotify_api_base: ${{ secrets.GOTIFY_URL }}
          gotify_app_token: ${{ secrets.RUNNER_GOTIFY_TOKEN }}
          notification_title: 'GITEA: Home Assistant Config Check'
          notification_message: '🚀 Config check done!'