name: Home Assistant Config Check

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "main"
    paths:
      - "app-configs/rikku/homeassistant/**"

jobs:
  home-assistant-config-check:
    name: Home Assistant Configuration Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Gotify Notification (start check)
        uses: eikendev/gotify-action@master
        with:
          gotify_api_base: ${{ secrets.GOTIFY_URL }}
          gotify_app_token: ${{ secrets.RUNNER_GOTIFY_TOKEN }}
          notification_title: "GITEA: Home Assistant Config Check"
          notification_message: "Starting config check..."

      - name: 🚀 Run Home Assistant Configuration Check
        uses: https://git.trez.wtf/Trez.One/action-home-assistant@main
        with:
          path: "app-configs/rikku/homeassistant"
          version: "stable"

      - name: Gotify Notification (done)
        uses: eikendev/gotify-action@master
        with:
          gotify_api_base: ${{ secrets.GOTIFY_URL }}
          gotify_app_token: ${{ secrets.RUNNER_GOTIFY_TOKEN }}
          notification_title: "GITEA: Home Assistant Config Check"
          notification_message: "🚀 Config check done!"

      - name: Trigger Tar Valon Ansible Deploy
        run: |
          BRANCH="${GITHUB_REF_NAME}"
          curl -X POST \
            -H "Authorization: token ${{ secrets.BOT_GITEA_TOKEN }}" \
            -H "Content-Type: application/json" \
            "https://git.trez.wtf/api/v1/repos/Trez/tar-valon-ansible/actions/workflows/gitea_tar-valon_ansible_deploy.yml/dispatches" \
            -d "{\"ref\":\"${BRANCH}\"}"
