name: Renovate

on:
  schedule:
    - cron: "0/30 * * * *"
  workflow_dispatch:

env:
  RENOVATE_VERSION: "41.146.8"

jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Renovate Run
        env:
          DOCKER_HOST: tcp://dockerproxy:2375
        run: |
          docker run --rm \
            -e RENOVATE_PLATFORM=gitea \
            -e RENOVATE_ENDPOINT=https://git.trez.wtf/api/v1 \
            -e RENOVATE_TOKEN=${{ secrets.RENOVATE_BOT_TOKEN }} \
            -e LOG_LEVEL=${{ vars.RENOVATE_LOG_LEVEL }} \
            -e RENOVATE_GITHUB_COM_TOKEN=${{ secrets.RENOVATE_GITHUB_TOKEN }} \
            -e RENOVATE_CONFIG_FILE=renovate.json \
            -e RENOVATE_REPOSITORIES=trez/tar-valon-ansible \
            --volumes-from ${{ env.JOB_CONTAINER_NAME }} \
            -w ${GITHUB_WORKSPACE} \
            renovate/renovate:${{ env.RENOVATE_VERSION }}-full
