homeassistant:
  # Name of the location where Home Assistant is running
  name: "Rikku"
  # Location required to calculate the time the sun rises and sets
  latitude: 40
  longitude: -73
  # 'metric' for Metric, 'us_customary' for US Customary
  unit_system: us_customary
  # Pick yours from here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: "America/New_York"

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# automation: !include automations.yaml
# script: !include scripts.yaml
# scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies: 192.168.1.254

browser:

ingress:
  adguard:
    work_mode: ingress
    ui_mode: toolbar
    title: AdGuardHome
    icon: si:adguard
    url: http://adguard
  ha-fusion:
    work_mode: ingress
    ui_mode: toolbar
    title: HA Fusion
    icon: mdi:monitor-dashboard
    url: http://ha-fusion:5050